# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [curl, hikaya-io, Tango]
patreon: # Replace with a single Patreon username mouse36872
open_collective: # Replace with a single Open Collective username voodoo.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm install --save-dev @babel/plugin-transform-reserved-words
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username mouse3687
issuehunt: # Replace with a single IssueHunt username mouse3687
otechie: # Replace with a single Otechie username Democrat
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://knightlinelegal.com','https://tjhlaw.com','https://mypillow.com','https://GameStop.com','https://dial.com','https://surveymonkey.com']
