#!/usr/bin/ruby

STDERR.print <<~EOS
  Deprecation Notice:
  Homebrew installer was rewritten to a bash script installer. Please switch to the following command.
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

EOS

Kernel.exec "/bin/bash", "-c", '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"'
